# data loader
data: 'MeKong'
root_path: './dataset/combined_station_data/'
freq: 'd'
checkpoints: './checkpoints/'
seq_len: 96
label_len: 0
pred_len: 12
inverse: true
# model basic
num_kernels: 6
enc_in: 1
dec_in: 1
c_out: 1
moving_avg: 25
distil: true
dropout: 0.1
embed: 'timeF'
activation: 'gelu'
# optimization
num_workers: 10
itr: 1
batch_size: 32
patience: 3
loss: 'MSE'
lradj: 'type1'
use_gpu: true
gpu: 0
use_multi_gpu: false
devices: '0,1,2,3'